### PR TITLE
Explain prominently how to install to /usr/local

### PR DESCRIPTION
**Pull request by alexntt**

### CODE REVIEW

**Comment by jonparrott** [comment]
@alexntt I'm happy to merge this, but can you re-confirm that this is still necessary and that it does the right thing?

**Comment by alexntt** [comment]
Hi @jonparrott , I think the change is right, but the bug I opened for this was closed as "working as expected", so while I think it's correct, I suppose pypa thinks it's wrong, see: https://github.com/pypa/pip/issues/3563

**Comment by pfmoore** [comment]
I think pypa/pip#3563 was closed because we don't expect to change the default behaviour of ```get-pip.py```. But I think that adding a note on the use of ```--prefix``` to the docs is fine.

**Comment by alexntt** [comment]
> but can you re-confirm that this is still necessary and that it does the right thing?

```
$ docker run -it --rm centos:centos5 /bin/bash
# yum install epel-release --disablerepo=libselinux --disablerepo=updates
# yum install python-setuptools wget python26 --disablerepo=libselinux --disablerepo=updates
# md5sum /usr/bin/easy_install
6e55062cdaa4d19cd254821875eb675d  /usr/bin/easy_install
# wget --no-check-certificate https://bootstrap.pypa.io/get-pip.py
# python26 get-pip.py
# md5sum /usr/bin/easy_install
86d01bbcc03f7a93509e88ed1645c39e  /usr/bin/easy_install
```

```
$ docker run -it --rm centos:centos5 /bin/bash
# yum install epel-release --disablerepo=libselinux --disablerepo=updates
# yum install python-setuptools wget python26 --disablerepo=libselinux --disablerepo=updates
# md5sum /usr/bin/easy_install
6e55062cdaa4d19cd254821875eb675d  /usr/bin/easy_install
# wget --no-check-certificate https://bootstrap.pypa.io/get-pip.py
# python26 get-pip.py --prefix=/usr/local/
# md5sum /usr/bin/easy_install
6e55062cdaa4d19cd254821875eb675d  /usr/bin/easy_install
```

, so I think so.

**Comment by jonparrott** [comment]
Cool. LGTM. Thanks, @alexntt and @pfmoore. :)

**Pull request merged**
