### PR TITLE
Improve binary extension docs

### PR DESCRIPTION
**Pull request by thewtex**

### CODE REVIEW

**Comment by theacodes** [comment]
Thanks, @thewtex!

**Comment by thewtex** [comment]
Thanks for the lightning quick review and integration @theacodes ! :zap:

**Comment by dhermes** [comment]
https://packaging.python.org/guides/packaging-binary-extensions/ still says "Last Reviewed: 2013-12-08". Need to update?

**Comment by theacodes** [comment]
@dhermes probably. We've been removing those things from pages, so it'd be nice if someone sent a PR to do that to this page.

**Comment by dhermes** [comment]
I feel the nudge to send the PR :grinning: but I like those `:Page Status:` :Last Reviewed:` extras so it'd be sad if I gave them the ax. (Though I understand why they'd get stale.)

**Pull request merged**
