### PR TITLE
Prerequisites section

### PR DESCRIPTION
**Pull request by JoshuaAcosta**
I've created a rough draft of the prerequisites section. Please feel free to provide feedback on style, grammar, wording or anything else you see fit. Thanks.

### CODE REVIEW

**Comment by pfmoore** [comment]
You seem to have pulled in a whole load of other changes. Not sure what's going on here?

**Comment by JoshuaAcosta** [comment]
My mistake, this is my first pull request. Not really sure how that happened. I wanted to submit only my changes which were to the prerequisites.rst file. How can I fix this?

**Comment by pfmoore** [comment]
No problem. It does look like you are trying to merge from the wrong branch somehow. It looks like this PR is from your prerequisites branch to the develop branch here - but the default branch is master, so maybe you wanted to do a PR against that? I'm not 100% sure why we even have both develop and master here...

Hopefully someone who knows the repo branch structure better can advise you.

**Comment by alexwlchan** [comment]
It looks as if #214 has the commits you wanted. Why did you close that PR?

**Comment by JoshuaAcosta** [comment]
I closed #214 thinking I did it wrong. Should I close #215 and reopen #214? Really appreciate the help, learning growing pains.

**Comment by pfmoore** [comment]
#214 looks OK to me. I'd go with that one. One thing, though, you've added the file, but not referenced it from anywhere else, so it's not linked from the main document. You'll need some text in one of the existing pages linking to this (maybe add it to ```additional.rst``` as another additional topic?).

**Comment by JoshuaAcosta** [comment]
Thanks!

**Pull request closed without merging**
