### PR TITLE
[WIP] Intro to Packaging tutorials

### PR DESCRIPTION
**Pull request by souravsingh**
Created the introduction page to Packaging tutorials.If any additions are needed,please feel free to tell me.

### CODE REVIEW

**Comment by souravsingh** [comment]
Thanks a lot @amitsaha. I have implemented a few of your suggestions.

**Comment by ddbeck** [comment]
@souravsingh Thanks so much for diving into this, Sourav! This is a great start. Having something concrete to think about has really clarified some things about how to write this introductory material. But that also means I came up with a bunch of ideas for ways to change the section (and ways to update the style guide and so on). I don't mean to dump a to-do list on you here; rather, I'm going to write down some ideas and you can choose to work on what you like, or we can merge the changes and I (or others) can carry on from there.

(And now that I'm writing this stuff down, I see that you've made some changes based on @amitsaha's comments already. Thanks to you both!)

Content idea: Newer Python users may lack context or confidence in their abilities (e.g., being able to use `if … elif … else` is different from knowing to call it a conditional). In addition to _describing_ the skills they need, I'd like to _show_ them too, as a way for readers to test-in to the tutorial, rather than opt-out. For example, we might show a short script or interactive session (in which something is `import`ed and used), and then tell the reader that if they understood most of it then they're ready to continue (and maybe a link to a language-learning resource if they don't).

Style ideas:

* I'd like to address the reader more directly. So rather than the current frame of "This tutorial is for Python programmers…" I'd prefer to see something more along the lines of "This tutorial is for you if you'd like to learn to…"
* On a related note, I'd like to be careful about talking abstractly about "programmers" (because lots of people [don't usually identify as programmers](https://packaging.python.org/en/develop/contribute/#audience)—myself included). Switching to the second person makes it easier to avoid, too.
* Mirroring something I've added to the style notes on #194:  We should invite the users to build skills (e.g., "After you complete this tutorial, you'll be able to…" ) rather than expect them to already have a specific need (e.g., "those who […] are looking to share their work").

Thanks again!

**Comment by souravsingh** [comment]
About the Python Learning resource,I have a doubt about it
I am thinking of adding Hitchhiker's Guide to Python, is it good for novice resource?

**Comment by ddbeck** [comment]
Yeah, I'm unsure too. I like the Hitchhiker's Guide, but it's definitely aimed at people who already know quite a bit about programming, just not a lot about _Python_.  The Python.org home page links to [this page](https://wiki.python.org/moin/BeginnersGuide), which I don't love, but it could be a good placeholder until someone comes along with a better suggestion.

**Comment by ncoghlan** [comment]
For a Python Learning resource, I'd agree with just linking to the Beginner's wiki page for now, as interested folks can tweak that by asking for edit permissions as described in https://wiki.python.org/moin/FrontPage#use

Longer term, I suggested at the language summit a couple of years ago that it would make sense to split the main Python tutorial and the HOWTO guides out from the rest of the Python documentation, as the core developers of the reference interpreter aren't really the best people in the world to be maintaining a beginner's guide, and for both the core tutorial and the HOWTO guides, it's likely better to cover variations between versions inline within the text, rather than requiring people to choose the correct version up front.

There's a current discussion on replacing CPython's current Mercurial hosting setup with GitHub or GitLab (or a combination of the two), and once that's resolved, it becomes more feasible to talk about creating a separate docs repository for version independent guides. That would then create an opportunity to repeat what's being done here with the packaging tutorials: use the opportunity to get technical writers directly involved in the maintenance process.

**Comment by amitsaha** [comment]
@ddbeck I like the idea of having some example code and making the reader comfortable. I am trying to think of a good example - simple but useful. Is there any specific package in your mind that we will possibly ask the reader to install as they progress through the documentation? Ideally, if we can give an example now - using a module from the standard library to do something and then using a third party package to do it better/or an advanced version of it, that would good I think.

**Comment by ncoghlan** [comment]
One possible example would be the https://pypi.python.org/pypi/parse library lets you use str.format() style format strings to parse input, instead of producing output.

For an example that involves importing in the standard library version without introducing new concepts like regular expressions, then the standard library's pprint module could be compared with David Wolever's pprintpp.

For a more complex example that shows the benefits of wheel files, then the standard library re module could be compared with Matthew Barnett's regex module. However, that shouldn't be the main example, since it introduces both regular expressions and binary dependencies.

**Comment by amitsaha** [comment]
Great suggestions @ncoghlan !

**Comment by souravsingh** [comment]
Thanks for the suggestions @ncoglhan. I will start working on it.

**Comment by jonparrott** [comment]
@souravsingh hi! This PR is now quite old and hasn't been touched in a while. I'm going to close, but if you still want to get this merged please let me know and I'll be happy to review and merge. :)

**Pull request closed without merging**
